from typing import Any, Awaitable, Callable


def sleep_ms(ms: int) -> Awaitable[None]: ...
def sleep(seconds: float) -> Awaitable[None]: ...
def create_task(coro: Awaitable[Any]) -> Any: ...
def run(coro: Awaitable[Any]) -> Any: ...
def get_event_loop() -> Any: ...
def new_event_loop() -> Any: ...
def wait_for(coro: Awaitable[Any], timeout: float) -> Awaitable[Any]: ...
def wait_for_ms(coro: Awaitable[Any], timeout: int) -> Awaitable[Any]: ...
def gather(*aws: Awaitable[Any], return_exceptions: bool = False) -> Awaitable[Any]: ...
def start_server(
    client_connected_cb: Callable[..., Any],
    host: str,
    port: int,
    backlog: int = 5,
) -> Awaitable[Any]: ...
